### ISSUE TITLE
`Scope.Errors` not changed when a user control set to invisible

### ISSUE THREAD

**Issue by mzh3511** [GuOrg/Gu.Wpf.ValidationScope#22]
Hello, thanks for your `Gu.Wpf.ValidationScope`, but I catch 2 issues about it:
1. `Scope.Errors` not changed when a user control set to invisible
I mean, I have a window contains some textboxes and 2 user controls, all textboxes and user controls have the validation error, when I set one user control invisible, items of the `Scope.Errors` that belongs to this user control do not disappear.

2. If I have a `DataTemplateSelector` and a group of `RadioButton`
There's a window contains a group of `Radio Button`, when the user checks one `Radio Button`, it will run to `DataTemplateSelector.SelectTemplate` method to get one data template to display, each data template has a user control. now there's an issue that when the display date template changed, its user control's validation errors still exist in the `Scope.Errors`

**Comment by mzh3511** [comment]
Just by the way, I have validation errors both from `IDataErrorInfo` and `ValidationRule`, those not disappeared errors are from `ValidationRule`

**Comment by JohanLarsson** [comment]
Thanks for reporting!

**Comment by JohanLarsson** [comment]
Fixed and added UI-tests.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Wpf.ValidationScope/0.2.3
